services:
  jenkins:
    image: jameslanham/home-intranet-jenkins:latest
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 50000:50000
    networks:
      - home-intranet-nginx
      - jenkins
    environment:
      VIRTUAL_HOST: "jenkins.intranet.local"
      VIRTUAL_PROTO: "http"
      VIRTUAL_PORT: 8080
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  agent:
    image: jenkins/ssh-agent:jdk17
    container_name: jenkins-agent
    privileged: true
    user: root
    expose:
      - 22
    networks:
      - jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${PUBLIC_KEY}
    restart: unless-stopped

networks:
  home-intranet-nginx:
    external: true
  jenkins:
    driver: bridge
